apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mediawiki-service
spec:
  selector:
    app: mediawiki
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
